name: Build and deploy poc-lfs-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Verificar ffmpeg no repo
        run: |
          dir src\WebsupplyConnect.API\Tools\ffmpeg.exe
          (Get-Item src\WebsupplyConnect.API\Tools\ffmpeg.exe).Length
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
      - name: Restore dependencies
        run: dotnet restore src/WebsupplyConnect.API --runtime win-x64
      - name: Build application
        run: dotnet build src/WebsupplyConnect.API --configuration Release --no-restore
      - name: Publish application
        run: dotnet publish src/WebsupplyConnect.API --configuration Release --output ./publish --self-contained --runtime win-x64 --no-restore
      - name: Verificar ffmpeg no publish
        run: |
          dir publish\Tools\ffmpeg.exe
          (Get-Item publish\Tools\ffmpeg.exe).Length
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_63A6E136A49D4E37826E18D65C0516EA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D5740ED3CEA44125940AB363C644C670 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_06C9CBD2D093479883E4ACBAD7A4DB8C }}
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'poc-lfs-deploy'
          slot-name: 'Production'
          package: ./publish
